### PR TITLE
feat: Upgrade to SDK v4

### PR DESCRIPTION
**Pull request by disq**
Hi there! This is a PR to update to our latest SDK! We are also rolling out hub shortly - https://hub.cloudquery.io so, once this PR is approved we can follow-up with additional PR so publish the plugin to our hub so users can enjoy dynamic searchable documentation for all versions and all tables.

**UPDATE**

I've created a `simple-analytics` team for you and created the plugin [on there](https://hub.cloudquery.io/plugins/source/simple-analytics/simple-analytics), although there are no versions published yet. We can only publish versions of plugins using the latest plugin SDK (v4) which this PR also covers.

I'd like to add one or few of you to the "Simple Analytics Team" on the hub to be able to publish versions, so please create a user at https://cloud.cloudquery.io/ and let me know your email used to register (`@simpleanalytics.com` domain preferably?) and we'll get it sorted. If you wish to discuss privately I'm `cq-kemal` on [our Discord](https://www.cloudquery.io/discord) or just email kemal@cloudquery.io.

### CODE REVIEW

**Review by hermanschaaf — APPROVED** [review]

**Review by yevgenypats — APPROVED** [review]

**Comment by adriaandotcom** [comment]
Thanks everybody! Can I merge this? Happy to do so.

**Comment by disq** [comment]
@adriaanvanrossum Yes please can you merge and also tag a `v2.0.0`?

**Comment by adriaandotcom** [comment]
Conside it done! Thanks all!

**Comment by adriaandotcom** [comment]
Can I add an admin to this repo to make this process easier for you guys?

**Comment by hermanschaaf** [comment]
@adriaanvanrossum I'm already able to merge PRs, if you're happy with us doing that going forward we can do so for future updates. Could you also add @yevgenypats and @disq to that list if you don't mind?

**Comment by adriaandotcom** [comment]
@yevgenypats @disq you're both invited: https://github.com/simpleanalytics/cq-source-simpleanalytics/invitations

**Pull request merged**
